In [2]:
import numpy as np
arr = np.array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])
arr

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

In [4]:
arr.dtype

dtype('float64')

In [5]:
arr.shape

(2, 3)

In [6]:
arr.reshape(3,2)

array([[-0.2047,  0.4789],
       [-0.5194, -0.5557],
       [ 1.9658,  1.3934]])

In [8]:
arr.astype(np.int64)

array([[0, 0, 0],
       [0, 1, 1]], dtype=int64)

In [10]:
arr1= np.random.randn(5,4)
arr1

array([[-1.46368426, -0.76250019, -0.38725039, -1.01852498],
       [-1.24753989,  1.70916186,  0.55294291,  1.15812431],
       [-1.65165943,  1.7692865 ,  0.3355713 , -0.73091893],
       [-0.68398315, -1.22088915,  0.61148291,  0.93491544],
       [ 0.42567673,  0.28795222, -0.72516025, -0.48905956]])

In [11]:
arr1[:3,:3]

array([[-1.46368426, -0.76250019, -0.38725039],
       [-1.24753989,  1.70916186,  0.55294291],
       [-1.65165943,  1.7692865 ,  0.3355713 ]])

In [12]:
arr_slice = arr1[:3,:3]

In [13]:
arr_slice[:2,1:]

array([[-0.76250019, -0.38725039],
       [ 1.70916186,  0.55294291]])

In [14]:
arr_slice[2,:]

array([-1.65165943,  1.7692865 ,  0.3355713 ])

In [15]:
arr_slice[:,:2]

array([[-1.46368426, -0.76250019],
       [-1.24753989,  1.70916186],
       [-1.65165943,  1.7692865 ]])

In [16]:
arr_slice[1:2,:2]

array([[-1.24753989,  1.70916186]])

In [17]:
arr2= np.random.randn(3,3,3)
arr2

array([[[ 0.51194686, -0.25742786,  0.24160491],
        [-0.03467224, -1.5027986 ,  0.67313853],
        [-1.00490324,  0.63556519,  0.85654256]],

       [[-0.12293279, -2.1601839 ,  0.42514688],
        [-0.24133413, -0.59167898, -0.21122644],
        [ 0.84517362, -1.02051562, -0.05896422]],

       [[-2.19181461,  0.7024096 , -0.37533827],
        [-0.51546536, -1.50559301,  0.95231075],
        [-2.18831932, -1.49159224,  1.64394474]]])

In [18]:
arr2.mean()

-0.2958139710809095

In [19]:
arr2[:,1].mean()

-0.3308132768983005

In [20]:
arr2[:,1,0].mean()

-0.26382391263294364

In [21]:
import csv
import numpy as np

 
f = open('example data.csv')
reader= csv.reader(f)
data = []

for line in reader: 
  data.append(line)
data

[['Participant', 'Block', 'Trial', 'reaction time', 'response'],
 ['e001', '1', '1', '1.100715931', 'l'],
 ['e001', '1', '2', '0.740111439', 'j'],
 ['e001', '1', '3', '0.573494424', 'l'],
 ['e001', '1', '4', '0.872829995', 'l'],
 ['e001', '1', '5', '0.485086876', 'l'],
 ['e001', '1', '6', '0.622875588', 'j'],
 ['e001', '1', '7', '0.367861597', 'l'],
 ['e001', '1', '8', '0.586825674', 'l'],
 ['e001', '1', '9', '0.868025656', 'j'],
 ['e001', '1', '10', '0.868025656', 'j'],
 ['e001', '2', '1', '0.701623485', 'l'],
 ['e001', '2', '2', '0.600994397', 'l'],
 ['e001', '2', '3', '0.901084375', 'l'],
 ['e001', '2', '4', '0.817473991', 'l'],
 ['e001', '2', '5', '0.517455377', 'l'],
 ['e001', '2', '6', '0.600896604', 'l'],
 ['e001', '2', '7', '0.70068142', 'l'],
 ['e001', '2', '8', '0.734383159', 'j'],
 ['e001', '2', '9', '0.634543216', 'j'],
 ['e001', '2', '10', '0.750579115', 'l'],
 ['e001', '3', '1', '0.851209335', 'l'],
 ['e001', '3', '2', '0.870069879', 'j'],
 ['e001', '3', '3', '0.751343338

In [22]:
data =np.array(data[1:]).reshape(3,30,5)
data

array([[['e001', '1', '1', '1.100715931', 'l'],
        ['e001', '1', '2', '0.740111439', 'j'],
        ['e001', '1', '3', '0.573494424', 'l'],
        ['e001', '1', '4', '0.872829995', 'l'],
        ['e001', '1', '5', '0.485086876', 'l'],
        ['e001', '1', '6', '0.622875588', 'j'],
        ['e001', '1', '7', '0.367861597', 'l'],
        ['e001', '1', '8', '0.586825674', 'l'],
        ['e001', '1', '9', '0.868025656', 'j'],
        ['e001', '1', '10', '0.868025656', 'j'],
        ['e001', '2', '1', '0.701623485', 'l'],
        ['e001', '2', '2', '0.600994397', 'l'],
        ['e001', '2', '3', '0.901084375', 'l'],
        ['e001', '2', '4', '0.817473991', 'l'],
        ['e001', '2', '5', '0.517455377', 'l'],
        ['e001', '2', '6', '0.600896604', 'l'],
        ['e001', '2', '7', '0.70068142', 'l'],
        ['e001', '2', '8', '0.734383159', 'j'],
        ['e001', '2', '9', '0.634543216', 'j'],
        ['e001', '2', '10', '0.750579115', 'l'],
        ['e001', '3', '1', '0.851209335

In [23]:
arr = data[:,:,3]
arr

array([['1.100715931', '0.740111439', '0.573494424', '0.872829995',
        '0.485086876', '0.622875588', '0.367861597', '0.586825674',
        '0.868025656', '0.868025656', '0.701623485', '0.600994397',
        '0.901084375', '0.817473991', '0.517455377', '0.600896604',
        '0.70068142', '0.734383159', '0.634543216', '0.750579115',
        '0.851209335', '0.870069879', '0.751343338', '0.634170544',
        '0.537303295', '0.634377835', '0.634377835', '0.617976476',
        '0.56806179', '1.017206362'],
       ['0.553048041', '1.017461229', '0.718231381', '0.635444501',
        '0.534133503', '0.567530534', '0.783894588', '1.000721935',
        '0.667932695', '1.235087536', '1.084109168', '1.084109168',
        '0.68880348', '0.85076379', '0.767524191', '0.435086102',
        '0.822451263', '0.717467912', '0.507026969', '0.800896679',
        '0.468055711', '0.734409212', '0.934326975', '0.734224198',
        '0.734224198', '0.550812384', '0.867853857', '0.967438178',
        '0.83

In [24]:
arr = arr.astype(np.float64)
arr

array([[1.10071593, 0.74011144, 0.57349442, 0.87283   , 0.48508688,
        0.62287559, 0.3678616 , 0.58682567, 0.86802566, 0.86802566,
        0.70162349, 0.6009944 , 0.90108438, 0.81747399, 0.51745538,
        0.6008966 , 0.70068142, 0.73438316, 0.63454322, 0.75057911,
        0.85120933, 0.87006988, 0.75134334, 0.63417054, 0.53730329,
        0.63437784, 0.63437784, 0.61797648, 0.56806179, 1.01720636],
       [0.55304804, 1.01746123, 0.71823138, 0.6354445 , 0.5341335 ,
        0.56753053, 0.78389459, 1.00072194, 0.66793269, 1.23508754,
        1.08410917, 1.08410917, 0.68880348, 0.85076379, 0.76752419,
        0.4350861 , 0.82245126, 0.71746791, 0.50702697, 0.80089668,
        0.46805571, 0.73440921, 0.93432697, 0.7342242 , 0.7342242 ,
        0.55081238, 0.86785386, 0.96743818, 0.83463014, 0.61749166],
       [0.82356701, 0.87322797, 0.90627045, 0.70637496, 0.80632705,
        0.90620211, 0.80656379, 0.73944954, 0.79282702, 0.92408094,
        0.75613673, 0.50157319, 0.65211772, 0.

In [25]:
arr = arr.reshape(3,3,10)
arr

array([[[1.10071593, 0.74011144, 0.57349442, 0.87283   , 0.48508688,
         0.62287559, 0.3678616 , 0.58682567, 0.86802566, 0.86802566],
        [0.70162349, 0.6009944 , 0.90108438, 0.81747399, 0.51745538,
         0.6008966 , 0.70068142, 0.73438316, 0.63454322, 0.75057911],
        [0.85120933, 0.87006988, 0.75134334, 0.63417054, 0.53730329,
         0.63437784, 0.63437784, 0.61797648, 0.56806179, 1.01720636]],

       [[0.55304804, 1.01746123, 0.71823138, 0.6354445 , 0.5341335 ,
         0.56753053, 0.78389459, 1.00072194, 0.66793269, 1.23508754],
        [1.08410917, 1.08410917, 0.68880348, 0.85076379, 0.76752419,
         0.4350861 , 0.82245126, 0.71746791, 0.50702697, 0.80089668],
        [0.46805571, 0.73440921, 0.93432697, 0.7342242 , 0.7342242 ,
         0.55081238, 0.86785386, 0.96743818, 0.83463014, 0.61749166]],

       [[0.82356701, 0.87322797, 0.90627045, 0.70637496, 0.80632705,
         0.90620211, 0.80656379, 0.73944954, 0.79282702, 0.92408094],
        [0.75613673, 0.

In [27]:
mean = arr.mean(axis=2)
std = arr.std(axis=2)

In [28]:
mean

array([[0.70858528, 0.69597151, 0.71160967],
       [0.77134859, 0.77582387, 0.74434665],
       [0.82848908, 0.70206072, 0.91280362]])

In [29]:
std

array([[0.20953386, 0.10725999, 0.14739336],
       [0.22491085, 0.19947412, 0.15474352],
       [0.06952439, 0.12741546, 0.26069583]])